//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentQueries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Phrases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Phrases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudentQueries.Phrases", typeof(Phrases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sequence number &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidSequenceNumberException {
            get {
                return ResourceManager.GetString("InvalidSequenceNumberException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entities matched your queries.
        /// </summary>
        internal static string NoResultMatchedTheQuery {
            get {
                return ResourceManager.GetString("NoResultMatchedTheQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update request id: &apos;{0}&apos; cannot be treated due to the event being out of order.
        /// </summary>
        internal static string SequenceIsOutOfOrderException {
            get {
                return ResourceManager.GetString("SequenceIsOutOfOrderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A student with &apos;{0}&apos; already exist.
        /// </summary>
        internal static string StudentAlreadyExistException {
            get {
                return ResourceManager.GetString("StudentAlreadyExistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update request for student with aggregate id: &apos;{0}&apos; Already treated.
        /// </summary>
        internal static string StudentAlreadyUpdatedException {
            get {
                return ResourceManager.GetString("StudentAlreadyUpdatedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student with aggregate id: &apos;{0}&apos; not found.
        /// </summary>
        internal static string StudentNotFoundException {
            get {
                return ResourceManager.GetString("StudentNotFoundException", resourceCulture);
            }
        }
    }
}
